version: '3'

services:
  # Сервис для вашего телеграм бота
  ars_inform:
    build: . # Ссылка на Dockerfile в текущей папке
    networks:
      - app-network # Указываем, что бот принадлежит к сети app-network
    container_name: ars_inform_bot # Задаем сетевое имя для контейнера
    volumes: # Монтируем папку с кодом приложения в контейнер
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # network_mode: host


# Определяем сеть для связи между сервисами
networks:
  app-network:
    driver: bridge
    name: ars_inform # Задаем имя сети

