version: '3'

services:
  # Сервис для вашего телеграм бота
  ars_inform:
    build: . # Ссылка на Dockerfile в текущей папке
    depends_on:
      - db # Указываем, что бот зависит от базы данных
    environment:
      - DATABASE_URL=postgres://postgres:postgres@bd:5432/postgres # Переменная окружения для подключения к базе данных
    networks:
      - app-network # Указываем, что бот принадлежит к сети app-network
    container_name: ars_inform_bot # Задаем сетевое имя для контейнера
    volumes: # Монтируем папку с кодом приложения в контейнер
      - ./:/app

  # Сервис для postgres
  db:
    build:
      context: . # путь к папке с Dockerfile
      dockerfile: Dockerfile.bd # имя файла
    environment:
      - POSTGRES_PASSWORD=postgres # Устанавливаем пароль для пользователя postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Монтируем том для хранения данных
    networks:
      - app-network # Указываем, что база данных принадлежит к сети app-network
    container_name: ars_inform_bd # Задаем сетевое имя для контейнера

# Определяем сеть для связи между сервисами
networks:
  app-network:
    driver: bridge
    name: ars_inform # Задаем имя сети

# Определяем том для хранения данных postgres
volumes:
  postgres_data:
    driver: local # Указываем драйвер для тома
    driver_opts: # Указываем опции для драйвера
      type: none # Тип тома - none
      device: ../postgres_data # Устройство - папка на хосте
      o: bind # Опция - привязка
